2023-05-26 23:26:49.5693|ERROR|ClassHelper.LogHelper|System.Exception: Internal Server Error
   at KSP3.DesktopApp.ServiceCaller.ApiClient.<RequestAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\ApiCLient.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.ServiceCaller.BaseCaller.<TryCallServiceAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\BaseCaller.cs:line 17
2023-05-26 23:27:53.4313|ERROR|ClassHelper.LogHelper|System.Exception: Internal Server Error
   at KSP3.DesktopApp.ServiceCaller.ApiClient.<RequestAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\ApiCLient.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.ServiceCaller.BaseCaller.<TryCallServiceAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\BaseCaller.cs:line 17
2023-05-26 23:32:43.1749|ERROR|ClassHelper.LogHelper|System.Exception: Internal Server Error
   at KSP3.DesktopApp.ServiceCaller.ApiClient.<RequestAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\ApiCLient.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.ServiceCaller.BaseCaller.<TryCallServiceAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\BaseCaller.cs:line 17
2023-05-26 23:57:24.4622|ERROR|ClassHelper.LogHelper|System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.ServiceCaller.ApiClient.<RequestAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\ApiCLient.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.ServiceCaller.BaseCaller.<TryCallServiceAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\BaseCaller.cs:line 17
2023-05-26 23:57:53.2574|ERROR|ClassHelper.LogHelper|System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.ServiceCaller.ApiClient.<RequestAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\ApiCLient.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.ServiceCaller.BaseCaller.<TryCallServiceAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\BaseCaller.cs:line 17
2023-05-26 23:58:48.7240|ERROR|ClassHelper.LogHelper|System.Exception: Vui lòng nh­p Tên công théc
   at KSP3.DesktopApp.ServiceCaller.ApiClient.<RequestAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\ApiCLient.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.ServiceCaller.BaseCaller.<TryCallServiceAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\BaseCaller.cs:line 17
2023-05-26 23:59:34.5460|ERROR|ClassHelper.LogHelper|System.Exception: Vui lòng nhập Tên công thức
   at KSP3.DesktopApp.ServiceCaller.ApiClient.<RequestAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\ApiCLient.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.ServiceCaller.BaseCaller.<TryCallServiceAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\BaseCaller.cs:line 17
